---
# tasks file for kibana
- name: Add vars
  include_vars: main.yml

- name: Add kibana-repo
  template:
    src: templates/kibana-repo.j2
    dest: /etc/yum.repos.d/kibana-repo.repo

- name: Install kibana
  dnf:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ packages }}"

- name: Add kibana elastic-config
  template:
    src: templates/kibana-config.j2
    dest: /etc/kibana/kibana.yml

- name: Allow firewalld
  firewalld:
    port: "{{ kibana_port_firewall }}"
    state: enabled
    permanent: yes
    immediate: yes

- name: Start kibana
  service:
    name: "{{ item.name }}"
    state: started
    enabled: yes
  loop: "{{ services }}"
