---
# tasks file for elastic
- name: Add variables
  include_vars: main.yml

- name: Add elasticsearch key
  raw: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add repo
  template:
    src: templates/elastic-repo.j2
    dest: /etc/yum.repos.d/elastic-repo.repo

- name: Install elasticsearch
  dnf: 
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ packages }}"

- name: Backup elastic-config
  copy:
    src: /etc/elasticsearch/elasticsearch.yml
    dest: ~/elasticsearch.yml
    remote_src: yes

- name: Add elasticsearch.yml
  template:
    src: templates/elastic-config.j2
    dest: /etc/elasticsearch/elasticsearch.yml

- name: Add sysconfig elasticsearch
  template:
    src: templates/sysconfig-elastic.j2
    dest: /etc/sysconfig/elasticsearch

- name: Add systemd 
  template:
    src: templates/elastic-systemd.j2
    dest: /usr/lib/systemd/system/elasticsearch.service

- name: Allow firewalld
  firewalld:
    port: "{{ port_elastic_firewall }}"
    state: enabled
    permanent: yes
    immediate: yes

- name: Start service
  service:
    daemon_reload: yes
    name: "{{ item.name }}"
    state: started
    enabled: yes
  loop: "{{ services }}"

